"""empty message

Revision ID: 2ccb186ffe48
Revises: ee1712bf5c12
Create Date: 2022-07-25 09:44:08.910261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccb186ffe48'
down_revision = 'ee1712bf5c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Phase', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Phase', 'end_date')
    # ### end Alembic commands ###
