"""empty message

Revision ID: 92960c651ae2
Revises: 
Create Date: 2022-07-22 21:47:22.473834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92960c651ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Engagement',
    sa.Column('engagement_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('expect_hours', sa.BigInteger(), nullable=False),
    sa.Column('actual_hours', sa.BigInteger(), nullable=False),
    sa.Column('internal_hours', sa.BigInteger(), nullable=True),
    sa.Column('subb_hours', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    op.create_table('Group',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('phase_id', sa.BigInteger(), nullable=False),
    sa.Column('internal_hours', sa.BigInteger(), nullable=True),
    sa.Column('subb_hours', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('GroupMember',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('phase_id', sa.BigInteger(), nullable=False),
    sa.Column('expect_hours', sa.BigInteger(), nullable=False),
    sa.Column('actual_hours', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'phase_id')
    )
    op.create_table('Member',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('employee', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('Phase',
    sa.Column('phase_id', sa.BigInteger(), nullable=False),
    sa.Column('engagement_id', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('step', sa.BigInteger(), nullable=False),
    sa.Column('expect_hours', sa.BigInteger(), nullable=False),
    sa.Column('actual_hours', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('phase_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Phase')
    op.drop_table('Member')
    op.drop_table('GroupMember')
    op.drop_table('Group')
    op.drop_table('Engagement')
    # ### end Alembic commands ###
