"""empty message

Revision ID: e68a4bbda5e1
Revises: 2ccb186ffe48
Create Date: 2022-07-25 09:49:43.401103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68a4bbda5e1'
down_revision = '2ccb186ffe48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Engagement', 'engagement_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('Group', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Group_group_id_seq"\'::regclass)'))
    op.alter_column('Group', 'phase_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('GroupMember', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('Phase', 'phase_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Phase_phase_id_seq"\'::regclass)'))
    op.alter_column('Phase', 'engagement_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('Phase', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Phase', 'group_id',
               existing_type=sa.String(length=30),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('Phase', 'engagement_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('Phase', 'phase_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Phase_phase_id_seq"\'::regclass)'))
    op.alter_column('GroupMember', 'group_id',
               existing_type=sa.String(length=30),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('Group', 'phase_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('Group', 'group_id',
               existing_type=sa.String(length=30),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Group_group_id_seq"\'::regclass)'))
    op.alter_column('Engagement', 'engagement_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
